CREATE DATABASE IF NOT EXISTS cars;
USE cars;
CREATE TABLE IF NOT EXISTS Users(
	id INT AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);
INSERT INTO Users VALUES(null, "Admin", "1234");
